id: IE3AA94E2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:45:40+00:00'
last_modified: '2022-06-08T11:41:27.179884+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1291
  title: མཁའ་འགྲོ་མ་སེངྒེའི་གདོང་ཅན་གྱི་རྗེས་གནང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E05D:
      image_group_id: I1CZ1803
      title: ''
      total_pages: 8
      order: 1
      base_file: E05D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
